export default [
  'Snowboards',
  'Has been to Disney World',
  'Has 2 dogs',
  'Likes winter more than summer',
  'Can name the state bird, fish, or flower',
  'Lives in a different state than they work',
  'Skis',
  'Has green eyes',
  'Has brown eyes',
  'Plays an instrument',
  'Owns a motorcycle',
  'Owns plants',
  'Has never been on a plane',
  'Has traveled to 5 or more countries',
  'Knows how to fly fish',
  'Can speak 2 or more languages',
  'Can juggle',
  'Has 2+ passports',
  'Has never broken a bone',
  'Knows how to salsa dance',
  'Has run a marathon',
  'Has been scuba diving',
  'Doesn’t like chocolate',
  'Practices yoga',
  'Allergic to cats',
  'Allergic to dogs',
  'Only child',
  'Oldest sibling',
  'Youngest sibling',
  'Left handed',
  'Has dyed their hair',
  'Is wearing green',
  'Has their CDL',
  'Was in marching band',
  'Is not enjoying this game',
  'Run for class president in school',
  'Can ride a horse',
  'Owns a truck',
];
